version = 0.1
[default.deploy.parameters]
stack_name = "q-business-plugins-apii"
resolve_s3 = true
s3_prefix = "q-business-plugins-apii"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
