version = 0.1
[default.deploy.parameters]
stack_name = "iot-pub-sub"
resolve_s3 = true
s3_prefix = "iot-pub-sub"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"file-sync-status\" Environment=\"dev\""
image_repositories = []
